"""Add call_transcript field

Revision ID: 6b13f7ac025b
Revises: da0d74d8bfbe
Create Date: 2025-08-09 20:23:09.710246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b13f7ac025b'
down_revision: Union[str, Sequence[str], None] = 'da0d74d8bfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('call_transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'call_transcript')
    # ### end Alembic commands ###
