"""add_property_fields_bathroom_deposit_bills

Revision ID: 73fac1f5624d
Revises: e0e0b4860ef8
Create Date: 2025-08-16 20:26:47.452539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fac1f5624d'
down_revision: Union[str, Sequence[str], None] = 'e0e0b4860ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('bathroom_count', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('deposit_cost', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('is_bills_included', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('availability_slots', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('availability_notes', sa.Text(), nullable=True))
    
    # Add NOT NULL columns with default values
    op.add_column('leads', sa.Column('availability_confirmed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leads', sa.Column('landlord_approval_pending', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'landlord_approval_pending')
    op.drop_column('leads', 'availability_confirmed')
    op.drop_column('leads', 'availability_notes')
    op.drop_column('leads', 'availability_slots')
    op.drop_column('leads', 'is_bills_included')
    op.drop_column('leads', 'deposit_cost')
    op.drop_column('leads', 'bathroom_count')
    # ### end Alembic commands ###
