"""add_system_prompt_to_calls

Revision ID: c68e49b9e5d3
Revises: df3c0d891c1d
Create Date: 2025-08-14 23:23:41.117303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68e49b9e5d3'
down_revision: Union[str, Sequence[str], None] = 'df3c0d891c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'system_prompt')
    # ### end Alembic commands ###
