"""Initial PostgreSQL migration with Lead and PropertyViewing tables

Revision ID: da0d74d8bfbe
Revises: 
Create Date: 2025-08-09 19:51:53.645748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0d74d8bfbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('move_in_date', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('yearly_wage', sa.Integer(), nullable=True),
    sa.Column('contract_length_enum', sa.Enum('LT_SIX_MONTHS', 'SIX_MONTHS', 'TWELVE_MONTHS', 'GT_TWELVE_MONTHS', name='contractlength'), nullable=True),
    sa.Column('name_confirmed', sa.Boolean(), nullable=False),
    sa.Column('budget_confirmed', sa.Boolean(), nullable=False),
    sa.Column('move_in_date_confirmed', sa.Boolean(), nullable=False),
    sa.Column('occupation_confirmed', sa.Boolean(), nullable=False),
    sa.Column('yearly_wage_confirmed', sa.Boolean(), nullable=False),
    sa.Column('contract_length_confirmed', sa.Boolean(), nullable=False),
    sa.Column('phase', sa.Enum('NEW', 'CONFIRM_INFO', 'BOOKING_VIEWING', 'VIEWING_BOOKED', 'COMPLETED', name='leadphase'), nullable=False),
    sa.Column('viewing_date', sa.String(length=50), nullable=True),
    sa.Column('viewing_time', sa.String(length=50), nullable=True),
    sa.Column('viewing_notes', sa.Text(), nullable=True),
    sa.Column('property_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('property_viewings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('property_address', sa.Text(), nullable=False),
    sa.Column('viewing_date', sa.String(length=50), nullable=False),
    sa.Column('viewing_time', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_viewings_id'), 'property_viewings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_viewings_id'), table_name='property_viewings')
    op.drop_table('property_viewings')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
