"""Add new fields for Charlie payload

Revision ID: e0e0b4860ef8
Revises: c68e49b9e5d3
Create Date: 2025-08-15 18:16:04.757355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e0b4860ef8'
down_revision: Union[str, Sequence[str], None] = 'c68e49b9e5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type first
    charlieoccupation_enum = sa.Enum('EMPLOYED', 'STUDENT', 'CRUISING', name='charlieoccupation')
    charlieoccupation_enum.create(op.get_bind(), checkfirst=True)
    
    # Add columns
    op.add_column('leads', sa.Column('occupation_type_enum', charlieoccupation_enum, nullable=True))
    op.add_column('leads', sa.Column('address_line_1', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('bedroom_count', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('availability_at', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('property_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'property_cost')
    op.drop_column('leads', 'availability_at')
    op.drop_column('leads', 'bedroom_count')
    op.drop_column('leads', 'address_line_1')
    op.drop_column('leads', 'occupation_type_enum')
    
    # Drop the enum type
    charlieoccupation_enum = sa.Enum(name='charlieoccupation')
    charlieoccupation_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
